[package]
name = "bomtoon"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs.git", version = "0.3.0", features = ["json"] }
arrayvec = { version = "0.7.8", default-features = false, features = ["serde"] }
chinese-number = { version = "0.8.2", default-features = false, features = ["number-to-chinese"] }
itoa = "1.0.18"
serde = { version = "1.0.229", default-features = false }
strum = { version = "0.28.0", default-features = false, features = ["derive"] }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"
